# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "blog" # the url of your github pages

# site information used in page title, meta data etc.
title: ""
description:

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: YCChen
author-bio: Software Engineer # change to false to hide
author-image: head.jpeg # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
  - text: About
    permalink: about
  - text: Category
    permalink: category

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: ""
footer-msg-link:

# Build settings
markdown: kramdown

exclude:
  - node_modules

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

include: ["node_modules/tailwindcss"]
